### ISSUE TITLE
Add UNAN rules in wiki?

### ISSUE THREAD

**Issue by CatsAreFluffy** [username5243/UNAN-calculator#1]

**Comment by aarextiaokhiao** [comment]
That would be suggestions to be added in this code.

**Comment by username5243** [comment]
I have added a file with rules up to w^w.

Should I "close" this now?

**Comment by CatsAreFluffy** [comment]
Well, 2 entry arrays only reach w^2 AFAIK.

**Comment by username5243** [comment]
It basically scans all the way through. If there's 0 at the first entry, it moves to the second. If no 0 there,it goes to the third. Continue until it finds a nonzero number.

**Comment by CatsAreFluffy** [comment]
But what happens with `[0,0,0]`? No rule handles this

**Comment by username5243** [comment]
The last entry would be 0. SO the 0s get cut until there's just one 0, where it becomse 1[0]b = 1*b
