### ISSUE TITLE
Change default array?

### ISSUE THREAD

**Issue by CatsAreFluffy** [username5243/UNAN-calculator#2]
2[3]3 is the largest array that results in a reasonable number (65536).

**Comment by CatsAreFluffy** [comment]
Actually, 3[3]2 is larger at 7625597484987.

**Comment by CatsAreFluffy** [comment]
Sadly, even 3[3]3 is too large (3^^7625597484987)

**Comment by CatsAreFluffy** [comment]
3[2]3 also becomes 3^^3 and it can be reversed to 3[0,1]2 which could be a good intro to linear arrays.

**Comment by username5243** [comment]
I think I will change it to 3[0,1]2 with the linear array update.

**Comment by username5243** [comment]
Done.
